<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\icon3.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="vcpkg\**" />
    <Compile Remove=".env\**" />
    <!-- This ensures your C-Engine DLL is copied directly to the output folder -->
    <None Include="..\Engine\fast_search.dll">
      <Link>fast_search.dll</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
